// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIG-AR6MtH5ptHw432P0SLi3s56AScfHU',
    appId: '1:169120042891:web:eeecda7ba1ea2f8ee9a98e',
    messagingSenderId: '169120042891',
    projectId: 'quick-chat-a5e58',
    authDomain: 'quick-chat-a5e58.firebaseapp.com',
    storageBucket: 'quick-chat-a5e58.firebasestorage.app',
    measurementId: 'G-TYM9Y89L2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsz8awRezjznXBW8D8iV0uH_2v-tP2_Co',
    appId: '1:169120042891:android:e2037009634d121ee9a98e',
    messagingSenderId: '169120042891',
    projectId: 'quick-chat-a5e58',
    storageBucket: 'quick-chat-a5e58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-PL7p8w2uLVxiA4pCB24YfMQqpBMTU8w',
    appId: '1:169120042891:ios:b829e5ea45da6f31e9a98e',
    messagingSenderId: '169120042891',
    projectId: 'quick-chat-a5e58',
    storageBucket: 'quick-chat-a5e58.firebasestorage.app',
    androidClientId:
        '169120042891-8bngljs9iuo43qfjqdidp9607onb73jq.apps.googleusercontent.com',
    iosClientId:
        '169120042891-789opejp5bhlq2i93mtahequ38dlbjen.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-PL7p8w2uLVxiA4pCB24YfMQqpBMTU8w',
    appId: '1:169120042891:ios:b829e5ea45da6f31e9a98e',
    messagingSenderId: '169120042891',
    projectId: 'quick-chat-a5e58',
    storageBucket: 'quick-chat-a5e58.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIG-AR6MtH5ptHw432P0SLi3s56AScfHU',
    appId: '1:169120042891:web:b0ceaf8a7595fcdde9a98e',
    messagingSenderId: '169120042891',
    projectId: 'quick-chat-a5e58',
    authDomain: 'quick-chat-a5e58.firebaseapp.com',
    storageBucket: 'quick-chat-a5e58.firebasestorage.app',
    measurementId: 'G-RZCHJ47R8C',
  );
}
