name: Flutter CI/CD with Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

  build:
    name: Build Flutter Web App
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web

  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: flutter-web-build
          path: build/web

      - name: Setup Firebase CLI
        uses: w9jds/firebase-action@v12
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  docker:
    name: Docker Build & Push (Optional)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t quick-chat-app .

      - name: Push Docker Image (Optional)
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "Skipping push since Docker Hub requires authentication."
